#!/usr/bin/env bash
set -euo pipefail

check_cmd() {
  command -v "$1" > /dev/null 2>&1
  return $?
}

say() {
    echo "$1"
}

err() {
  red=$(tput setaf 1 2>/dev/null || echo '')
  reset=$(tput sgr0 2>/dev/null || echo '')
  say "${red}ERROR${reset}: $1" >&2
  exit 1
}

get_architecture() {
  _ostype="$(uname -s)"
  _arch="$(uname -m)"
  _arm=("arm armhf aarch64 aarch64_be armv6l armv7l armv8l arm64e") # arm64
  _amd=("x86 x86pc i386 i686 i686-64 x64 x86_64 x86_64h athlon")    # amd64

  if [[ "${_arm[*]}" =~ ${_arch} ]]; then
    _arch="arm64"
  elif [[ "${_amd[*]}" =~ ${_arch} ]]; then
    _arch="amd64"
  elif [[ "${_arch}" != "ppc64le" ]]; then
    echo -e "ERROR: unsupported architecture \"${_arch}\"" >&2
    exit 2
  fi

  RETVAL="${_ostype}_${_arch}"
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

# This wraps curl or wget.
# Try curl first, if not installed, use wget instead.
downloader() {
  if check_cmd curl; then
    _dld=curl
  elif check_cmd wget; then
    _dld=wget
  else
    _dld='curl or wget' # to be used in error message of need_cmd
  fi

  if [ "$1" = --check ]; then
    need_cmd "$_dld"
  elif [ "$_dld" = curl ]; then
    curl -sSfL "$1" -o "$2"
  elif [ "$_dld" = wget ]; then
    wget "$1" -O "$2"
  else
    err "Unknown downloader"
  fi
}

check_latest_version() {
  local _executable="monorepo-diff-buildkite-plugin"
  local _repo="https://api.github.com/repos/buildkite-plugins/monorepo-diff-buildkite-plugin"
  local _version=""

  if check_cmd curl; then
    _version=$(curl -s "${_repo}/releases/latest" | grep -oE '"tag_name": "v[0-9]+\.[0-9]+\.[0-9]+"' | cut -d'"' -f4)
  elif check_cmd wget; then
    _version=$(wget -qO- "${_repo}/releases/latest" | grep -oE '"tag_name": "v[0-9]+\.[0-9]+\.[0-9]+"' | cut -d'"' -f4)
  fi

  if [[ "$_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
    true
  else
    _version=""
  fi

  RETVAL="$_version"
}

check_binary_version() {
  local _executable="monorepo-diff-buildkite-plugin"
  local _version=""

  _version=$(BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE=true ./${_executable} 2>&1 | grep -oE 'running monorepo-diff-buildkite-plugin ([0-9]+\.[0-9]+\.[0-9]+)' | cut -d' ' -f3)

  RETVAL="v${_version}"
}

get_version() {
  local _plugin=${BUILDKITE_PLUGINS:-""}
  local _version=""

  if [[ "$_plugin" =~ ^.*monorepo-diff-buildkite-plugin#?([^\"]+) ]]; then
    _version=${BASH_REMATCH[1]}
  fi

  if [[ "$_version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
    true
  else
    _version=""
  fi
    
  RETVAL="$_version"
}

download_binary_and_run() {
  get_architecture || return 1
  local _arch="$RETVAL"
  local _executable="monorepo-diff-buildkite-plugin"
  local _repo="https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin"

  get_version || return 1
  local _specified_version="$RETVAL"
  local _latest_version=""
  local _binary_version=""
  local test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"
  local _url=""

  if check_cmd "./${_executable}"; then
    if check_binary_version; then
      _binary_version="$RETVAL"
    else
      say "Warning: Could not determine binary version, will download fresh copy"
    fi
  fi

  if [[ "$test_mode" == "true" ]]; then
    true
  elif [ -z "${_specified_version}" ]; then
    check_latest_version || return 1
    _latest_version="$RETVAL"
    if [[ -z "$_binary_version" ]] || [[ "$_binary_version" != "$_latest_version" ]]; then
      _url=${_repo}/releases/latest/download/${_executable}_${_arch}
    fi
  else
    if [[ -z "$_binary_version" ]] || [[ "$_binary_version" != "$_specified_version" ]]; then
      _url=${_repo}/releases/download/${_specified_version}/${_executable}_${_arch}
    fi
  fi

  if [ -n "${_url}" ]; then
    if ! downloader "$_url" "$_executable"; then
      say "failed to download $_url"
      exit 1
    fi
  fi

  # todo: move it to a more secure place
  chmod +x ${_executable}
  
  ./${_executable}
}

download_binary_and_run "$@" || exit 1
